<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "scenecs_resource_settings"
 *
 * Auto generated by Extension Builder 2016-03-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Resource BackendSettings for Language Overlay',
	'description' => 'Enable alt and link fields for pages_language_overlay media.',
	'category' => 'be',
	'author' => 'SCENECS',
	'author_email' => 'scenecs@t-online.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);